default: &default
  adapter: postgresql
  pool: 8 
  host: localhost
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  username: shivanirails
  password: 123456
  encoding: utf8
  database: dating_app_development
